// ignore_for_file: public_member_api_docs

import 'package:hive/hive.dart';

part 'task.g.dart'; // This file will be generated by Hive for type adapters

@HiveType(typeId: 1) // Unique ID for Task type with Hive
class Task extends HiveObject {
  Task({required this.name, this.isChecked = false});
  @HiveField(0)
  late String name;

  @HiveField(1)
  late bool isChecked;
}
